# Site settings
url: http://templecoding.com # the base hostname & protocol for your site
#url: http://localhost:4000
title: Temple Coding
subtitle: code, technology and other geek stuff
default_bg: background/shoes.jpg
description: Hello, I'm Thiago Temple, a developer, geek and this is my site.
keywords: Thiago Temple, vintem, temple coding
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: vintem12
author: Thiago Temple
root: /vintem.github.io
search: true
share: true
readtime: true
triangleheader:	true
animated_fins: true
fin_color: "255,255,255"
disqus_shortname: templecodingenglish
github_username: vintem
github_repo_url: https://github.com/vintem/vintem.github.io

owner:
  name: Thiago Temple
  avatar: vintem.jpg 
  email: vintem@gmail.com
  description: Thiago Temple, developer, geek and this is my site.
  twitter: vintem12
  github: vintem
  linkedin: https://ca.linkedin.com/in/vintem
  instagram: vintem
  stackexchange: https://stackoverflow.com/users/186836/vintem
  
google_analytics: UA-41090209-2

links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: About
    url: /about
    external: false
  - title: Categories
    url: /categories
    
timezone: Canada/Eastern
future: true
highlighter: pygments
markdown: kramdown
paginate: 6
paginate_path: "/blog/page/:num"

permalink: /blog/:year/:month/:day/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Statcounter
statcounter_project_id: 5357260
statcounter_security_code: 14d7610a

exclude: ['bower.json', 'Gemfile', 'Gemfile.lock', 'README.md', 'CNAME']
