# Site settings
url: http://templecoding.com # the base hostname & protocol for your site
title: Temple Coding
subtitle: code, technology and other geek stuff
description: Thiago Temple, developer, geek and this is my site.
keywords: Thiago Temple, vintem, temple coding
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: vintem12
author: Thiago Temple
root: /vintem.github.io

github_username: vintem
github_repo_url: https://github.com/vintem/vintem.github.io

# Build settings
markdown: kramdown

subscribe_rss: /feed.xml
root: /
paginate: 10

paginate_path: "/blog/page/:num"

permalink: /blog/:year/:month/:day/:title/

category_dir: categories

titlecase: false

simple_search: http://www.google.com/cse
simple_search_id: 001293680430809257884:fpqsxf5isbu

# Disqus Comments
disqus_short_name: templecodingenglish
disqus_show_comment_count: false

# Statcounter
statcounter_project_id: 9135601
statcounter_security_code: 1fd2b255

google_analytics_tracking_id: UA-41090209-2

twitter_tweet_button: true

# Facebook Like
facebook_like: true

gems:
  - jekyll-sitemap

exclude: ['bower.json', 'Gemfile', 'Gemfile.lock', 'README.md', 'CNAME']
